basePath: /
definitions:
  request.ItemRequest:
    properties:
      description:
        example: Item A
        type: string
      item_code:
        example: ABC123
        type: string
      quantity:
        example: 7
        type: integer
    type: object
  request.OrderRequest:
    properties:
      customer_name:
        example: Fildza
        type: string
      items:
        items:
          $ref: '#/definitions/request.ItemRequest'
        type: array
      ordered_at:
        example: "2024-03-10T19:00:00+07:00"
        type: string
    type: object
  request.UpdateItemRequest:
    properties:
      description:
        example: Item A
        type: string
      id:
        example: ce135609-1426-4011-bb95-8c475c45fb33
        type: string
      item_code:
        example: ABC123
        type: string
      quantity:
        example: 7
        type: integer
    type: object
  request.UpdateOrderRequest:
    properties:
      customer_name:
        example: Fildza
        type: string
      items:
        items:
          $ref: '#/definitions/request.UpdateItemRequest'
        type: array
      ordered_at:
        example: "2024-03-10T19:00:00+07:00"
        type: string
    type: object
  response.ItemResponse:
    properties:
      description:
        type: string
      id:
        type: string
      item_code:
        type: string
      quantity:
        type: integer
    type: object
  response.OrderResponse:
    properties:
      customer_name:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/response.ItemResponse'
        type: array
      ordered_at:
        type: string
    type: object
  responses.TErrorResponse:
    properties:
      meta:
        $ref: '#/definitions/responses.TResponseMeta'
    type: object
  responses.TResponseMeta:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  responses.TSuccessResponse:
    properties:
      meta:
        $ref: '#/definitions/responses.TResponseMeta'
      results: {}
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a simple service for managing orders
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /orders:
    get:
      description: Retrieve all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.TSuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.TErrorResponse'
      summary: Get all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create a new order with the provided order data
      parameters:
      - description: Order data
        in: body
        name: orderRequest
        required: true
        schema:
          $ref: '#/definitions/request.OrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.TErrorResponse'
      summary: Create a new order
      tags:
      - orders
  /orders/{order_id}:
    delete:
      description: Delete order by order ID
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.TSuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.TErrorResponse'
      summary: Delete order by ID
      tags:
      - orders
    get:
      description: Retrieve order details by order ID
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.OrderResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.TErrorResponse'
      summary: Get order by ID
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Update order details by order ID
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: string
      - description: Order details
        in: body
        name: updateOrderRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.TErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.TErrorResponse'
      summary: Update order by ID
      tags:
      - orders
swagger: "2.0"
